name: Cabal dependency and incremental build caches
runs:
  using: composite
  steps:
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cabal/store
        key: cabal-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-${{ runner.os }}
    - name: Cache incremental build
      uses: actions/cache@v3
      with:
        path: ./dist-newstyle/
        key: dist-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          dist-${{ runner.os }}
