name: Cabal dependency and incremental build caches
runs:
  using: composite
  steps:
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.local/state/cabal/store/
        key: cabal-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          cabal-${{ runner.os }}-${{ runner.arch }}
    - name: Cache incremental build
      uses: actions/cache@v4
      with:
        path: ./dist-newstyle/
        key: dist-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
        restore-keys: |
          dist-${{ runner.os }}-${{ runner.arch }}
